/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author elton
 */
public class Relatorios extends javax.swing.JFrame {

    /**
     * Creates new form Excluir
     */
    //Tela simples onde será mostrado quais os possiveis relatorios
    public Relatorios() {
        initComponents();
        //Abrir tela no meio
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonExcluirVoltar = new javax.swing.JButton();
        jButtonPDFDescricao = new javax.swing.JButton();
        jButtonPDFSetor = new javax.swing.JButton();
        jButtonPDFSetor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(94, 90, 96));
        jPanel2.setBorder(null);

        jButtonExcluirVoltar.setBackground(new java.awt.Color(94, 90, 96));
        jButtonExcluirVoltar.setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        jButtonExcluirVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluirVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        jButtonExcluirVoltar.setText("Voltar");
        jButtonExcluirVoltar.setToolTipText("Voltar ao Menu Principal");
        jButtonExcluirVoltar.setBorder(null);
        jButtonExcluirVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonExcluirVoltar.setFocusCycleRoot(true);
        jButtonExcluirVoltar.setFocusPainted(false);
        jButtonExcluirVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExcluirVoltar.setRequestFocusEnabled(false);
        jButtonExcluirVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirVoltarMouseClicked(evt);
            }
        });
        jButtonExcluirVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirVoltarActionPerformed(evt);
            }
        });

        jButtonPDFDescricao.setBackground(new java.awt.Color(94, 90, 96));
        jButtonPDFDescricao.setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        jButtonPDFDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPDFDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PDFBranco.png"))); // NOI18N
        jButtonPDFDescricao.setText("Descrição");
        jButtonPDFDescricao.setToolTipText("Voltar ao Menu Principal");
        jButtonPDFDescricao.setBorder(null);
        jButtonPDFDescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPDFDescricao.setFocusCycleRoot(true);
        jButtonPDFDescricao.setFocusPainted(false);
        jButtonPDFDescricao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPDFDescricao.setRequestFocusEnabled(false);
        jButtonPDFDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPDFDescricaoMouseClicked(evt);
            }
        });
        jButtonPDFDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFDescricaoActionPerformed(evt);
            }
        });

        jButtonPDFSetor.setBackground(new java.awt.Color(94, 90, 96));
        jButtonPDFSetor.setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        jButtonPDFSetor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPDFSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PDFBranco.png"))); // NOI18N
        jButtonPDFSetor.setText("Setor");
        jButtonPDFSetor.setToolTipText("Voltar ao Menu Principal");
        jButtonPDFSetor.setBorder(null);
        jButtonPDFSetor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPDFSetor.setFocusCycleRoot(true);
        jButtonPDFSetor.setFocusPainted(false);
        jButtonPDFSetor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPDFSetor.setRequestFocusEnabled(false);
        jButtonPDFSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPDFSetorMouseClicked(evt);
            }
        });
        jButtonPDFSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFSetorActionPerformed(evt);
            }
        });

        jButtonPDFSetor1.setBackground(new java.awt.Color(94, 90, 96));
        jButtonPDFSetor1.setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        jButtonPDFSetor1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPDFSetor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PDFBranco.png"))); // NOI18N
        jButtonPDFSetor1.setText("Responsável");
        jButtonPDFSetor1.setToolTipText("Voltar ao Menu Principal");
        jButtonPDFSetor1.setBorder(null);
        jButtonPDFSetor1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPDFSetor1.setFocusCycleRoot(true);
        jButtonPDFSetor1.setFocusPainted(false);
        jButtonPDFSetor1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPDFSetor1.setRequestFocusEnabled(false);
        jButtonPDFSetor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPDFSetor1MouseClicked(evt);
            }
        });
        jButtonPDFSetor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFSetor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExcluirVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDFDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDFSetor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDFSetor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPDFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPDFSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPDFSetor1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButtonExcluirVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirVoltarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirVoltarMouseClicked

    private void jButtonExcluirVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirVoltarActionPerformed
        //Botão que retorna a JanelaHome
        //Criando a janelaHome e depois setando ela como visivel e posterior utilizando o dispose para "fechar a relatorios"
        Home janelaHome = new Home();
        janelaHome.setVisible(rootPaneCheckingEnabled);
        dispose();
    }//GEN-LAST:event_jButtonExcluirVoltarActionPerformed

    private void jButtonPDFDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPDFDescricaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPDFDescricaoMouseClicked

    private void jButtonPDFDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFDescricaoActionPerformed
        //Botão que acessa ao Relatorios de PDF por Descrição
        //Criando a telaDescricao e depois setando ela como visivel e posterior utilizando o dispose para "fechar a relatorios"
        RelDescricao telaDescricao = new RelDescricao();
        telaDescricao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPDFDescricaoActionPerformed

    private void jButtonPDFSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPDFSetorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPDFSetorMouseClicked

    private void jButtonPDFSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFSetorActionPerformed
        //Botão que acessa ao Relatorios de PDF por Setor
        //Criando a telaSetor e depois setando ela como visivel e posterior utilizando o dispose para "fechar a relatorios"
        RelSetor telaSetor = new RelSetor();
        telaSetor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPDFSetorActionPerformed

    private void jButtonPDFSetor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPDFSetor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPDFSetor1MouseClicked

    private void jButtonPDFSetor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFSetor1ActionPerformed
        //Botão que acessa ao Relatorios de PDF por Responsavel
        //Criando a telaResponsavel e depois setando ela como visivel e posterior utilizando o dispose para "fechar a relatorios"
        RelResponsavel telaResponsavel = new RelResponsavel();
        telaResponsavel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPDFSetor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluirVoltar;
    private javax.swing.JButton jButtonPDFDescricao;
    private javax.swing.JButton jButtonPDFSetor;
    private javax.swing.JButton jButtonPDFSetor1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
